{% set name = "playwright-stealth" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ac57e51873190da5e653e03720e948c8f0a3d06b098f1d56763103d23ee48143

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - poetry-core
    - pip
  run:
    - playwright >=1.40.0
    - python >={{ python_min }}
    - setuptools
    - playwright-python

test:
  imports:
    - playwright_stealth
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AtuboDad/playwright_stealth
  summary: playwright stealth
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
